language: java
jdk:
  - openjdk14
  - oraclejdk14
before_install: "cp .travis.settings.xml $HOME/.m2/settings.xml"
deploy:
  provider: script
  script: "mvn deploy"
  skip_cleanup: true
  on:
    branch: master
    jdk: openjdk14
